import Logo from './Ubereats.jpg'
import './json.css'
const uberJson=[{
     FDS:<img src={Logo}/>,
    order:"12345",
    name:"俺のガパ・・",
    menu:"カレーガパオライス ���g",
    opt:"パクチー大盛",
    数量:"1",
    aded:"11:55",
    pick_up:"12:10",
    status:""
},
{   FDS:<img src={Logo}/>,
    order:"12545",
    name:"俺のガパ・・",
    menu:"カレーガパオライス ���g",
    opt:"パクチー大盛",
    数量:"1",
    aded:"11:55",
    pick_up:"12:10",
    status:""
},
{   FDS:<img src={Logo}/>,
    order:"354764",
    name:"俺のガパ・・",
    menu:"カレーガパオライス ���g",
    opt:"パクチー大盛",
    数量:"1",
    aded:"11:55",
    pick_up:"12:10",
    status:""
},
{   FDS:<img src={Logo}/>,
    order:"45374",
    name:"俺のガパ・・",
    menu:"カレーガパオライス ���g",
    opt:"パクチー大盛",
    数量:"1",
    aded:"11:55",
    pick_up:"12:10",
    status:""
},
{   FDS:<img src={Logo}/>,
    order:"12345",
    name:"俺のガパ・・",
    menu:"カレーガパオライス ���g",
    opt:"パクチー大盛",
    数量:"1",
    aded:"11:55",
    pick_up:"12:10",
    status:""
},
{   FDS:<img src={Logo}/>,
    order:"454574",
    name:"俺のガパ・・",
    menu:"カレーガパオライス ���g",
    opt:"パクチー大盛",
    数量:"1",
    aded:"11:55",
    pick_up:"12:10",
    status:""
},
{   FDS:<img src={Logo}/>,
    order:"98354",
    name:"俺のガパ・・",
    menu:"カレーガパオライス ���g",
    opt:"パクチー大盛",
    数量:"1",
    aded:"11:55",
    pick_up:"12:10",
    status:""
},
{   FDS:<img src={Logo}/>,
    order:"17586",
    name:"俺のガパ・・",
    menu:"カレーガパオライス ���g",
    opt:"パクチー大盛",
    数量:"1",
    aded:"11:55",
    pick_up:"12:10",
    status:""
},
{   FDS:<img src={Logo}/>,
    order:"176474",
    name:"俺のガパ・・",
    menu:"カレーガパオライス ���g",
    opt:"パクチー大盛",
    数量:"1",
  
    aded:"11:55",
    pick_up:"12:10",
    status:""
},
{   FDS:<img src={Logo}/>,
    order:"86855",
    name:"俺のガパ・・",
    menu:"カレーガパオライス ���g",
    opt:"パクチー大盛",
    数量:"1",
    aded:"11:55",
    pick_up:"12:10",
    status:""
},
{   FDS:<img src={Logo}/>,
    order:"12345",
    name:"俺のガパ・・",
    menu:"カレーガパオライス ���g",
    opt:"パクチー大盛",
    数量:"1",
    aded:"11:55",
    pick_up:"12:10",
    status:""
},
{   FDS:<img src={Logo}/>,
    order:"12345",
    name:"俺のガパ・・",
    menu:"カレーガパオライス ���g",
    opt:"パクチー大盛",
    数量:"1",
    aded:"11:55",
    pick_up:"12:10",
    status:""
},
{   FDS:<img src={Logo}/>,
    order:"12345",
    name:"俺のガパ・・",
    menu:"カレーガパオライス ���g",
    opt:"パクチー大盛",
    数量:"1",
    aded:"11:55",
    pick_up:"12:10",
    status:""
}
]
export default uberJson;